(function(){
  'use strict';
  const cfg=window.BDAY_CONFIG||{}; const M=window.BdayMath; const T=window.BDAY_TEXT;
  const page=document.body.dataset.page||'home';
  const params=new URLSearchParams(location.search);
  const langs=['en','fr-CA','de'];
  const lang=langs.includes(params.get('lang'))?params.get('lang'):(localStorage.getItem('bday-language')||'en');
  const t=T[lang]||T.en; localStorage.setItem('bday-language',lang); document.documentElement.lang=t.locale;
  const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(s,o={})=>String(s).replace(/\{(\w+)\}/g,(_,k)=>o[k]??'');
  const path=(p)=>p+(p.includes('?')?'&':'?')+'lang='+encodeURIComponent(lang);
  const weekdayName=n=>t.weekdays[n-1]||'';
  const dateLabel=(y,m,d)=>`${d} ${t.months[m-1]} ${y}`;
  function flags(){return `<nav class="languages" aria-label="${esc(t.language)}">${[['en','us','English'],['fr-CA','ca','Français'],['de','de','Deutsch']].map(([l,c,n])=>`<a class="lang ${l===lang?'active':''}" href="${path(location.pathname.split('/').pop()||'index.html')}" hreflang="${l}" aria-label="${n}"><img src="assets/flags/${c}.svg" alt=""> <span>${n}</span></a>`).join('')}</nav>`}
  function header(){return `<header class="top"><a class="brand" href="${path('index.html')}"><span class="brand-mark">B</span><span><b>BDAY</b><small>METHOD</small></span></a><nav class="main-nav"><a href="${path('index.html')}#explore">${esc(t.explore)}</a><a href="${path('index.html')}#practice">${esc(t.practice)}</a><a href="${path('learn.html')}">${esc(t.learn)}</a></nav>${flags()}</header>`}
  function footer(){return `<footer class="footer"><div><b>BDAY METHOD</b><span> · ${esc(t.brand)}</span></div><nav><a href="${path('legal.html')}">${esc(t.legal)}</a><a href="${path('privacy.html')}">${esc(t.privacy)}</a><a href="mailto:${esc(cfg.email)}">${esc(t.contact)}</a></nav></footer>`}
  function shell(content){document.getElementById('site').innerHTML=`<a class="skip" href="#main">${esc(t.skip)}</a>${header()}<main id="main">${content}</main>${footer()}`;}
  function monthOptions(){return t.months.map((m,i)=>`<option value="${i+1}">${esc(m)}</option>`).join('')}
  function calculator(){return `<section class="panel calculator" id="calculator"><div class="section-kicker">${esc(t.free)} · ${esc(t.calculator)}</div><h2>${esc(t.calculator)}</h2><p>${esc(t.calcText)}</p><form id="calc-form" class="date-form"><label>${esc(t.day)}<input id="calc-day" type="number" min="1" max="31" value="4" required></label><label>${esc(t.month)}<select id="calc-month">${monthOptions()}</select></label><label>${esc(t.year)}<input id="calc-year" type="number" min="1" max="9999" value="1981" required></label><button class="button gold" type="submit">${esc(t.calculate)} <span>→</span></button></form><p class="fine">${esc(t.dateNote)} ${esc(t.gregorian)}</p><div id="calc-result" class="result" aria-live="polite"></div></section>`}
  function trailer(){return `<section class="trailer" id="explore"><div class="section-kicker">${esc(t.demoEye)}</div><div class="trailer-head"><div><h2>${esc(t.demoTitle)}</h2><p>${esc(t.demoText)}</p></div><label class="year-pick">${esc(t.year)}<input id="trailer-year" type="number" min="1" max="9999" value="2026"></label></div><div class="anchor-grid"><article><span class="tag">${esc(t.twins)}</span><h3>04/04 · 06/06</h3><p>4 April · 6 June</p><b id="pair-day"></b></article><article><span class="tag">${esc(t.reversals)}</span><h3>09/05 · 05/09</h3><p>9 May · 5 September</p><b id="reverse-day"></b></article><article><span class="tag">${esc(t.reversals)}</span><h3>11/07 · 07/11</h3><p>11 July · 7 November</p><b id="july-day"></b></article><article><span class="tag">${esc(t.pi)}</span><h3>14/03 · 03/14</h3><p>${esc(t.piNote)}</p><b id="pi-day"></b></article></div><div class="quick-test"><div><span class="tag">${esc(t.quickTest)}</span><h3>${fmt(t.question,{day:'Saturday'})}</h3></div><div class="choices" id="demo-choices">${t.weekdays.map((d,i)=>`<button data-answer="${i+1}">${esc(d)}</button>`).join('')}</div><p id="demo-feedback" class="feedback"></p></div></section>`}
  function practice(){return `<section class="practice" id="practice"><div class="section-kicker">${esc(t.practiceEye)}</div><h2>${esc(t.practiceTitle)}</h2><p>${esc(t.practiceText)}</p><div class="practice-tabs">${t.modes.map((m,i)=>`<button class="${i===0?'active':''}" data-mode="${i}">${esc(m)}</button>`).join('')}</div><div class="practice-card"><div id="practice-question"></div><label>${esc(t.answerLabel)}<select id="practice-answer">${t.weekdays.map((d,i)=>`<option value="${i+1}">${esc(d)}</option>`).join('')}</select></label><div class="practice-actions"><button class="button gold" id="practice-check">${esc(t.check)}</button><button class="button ghost" id="practice-new">${esc(t.newQuestion)}</button></div><p id="practice-feedback" class="feedback"></p><div class="scoreline"><span>${esc(t.score)}: <b id="practice-score">0</b></span><span>${esc(t.streak)}: <b id="practice-streak">0</b></span></div></div></section>`}
  function offer(){return `<section class="offer" id="offer"><div><div class="section-kicker">${esc(t.offerEye)}</div><h2>${esc(t.offerTitle)}</h2><p>${esc(t.offerText)}</p><ul>${t.included.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="offer-card"><div class="price">$9 <small>USD</small></div><p>${esc(t.once)}</p><a class="button gold full" href="${cfg.salesEnabled&&cfg.payhipUrl?esc(cfg.payhipUrl):'#access'}">${esc(t.buy)} <span>→</span></a><small>${esc(t.taxes)}</small></div></section>`}
  function access(){return `<section class="access panel" id="access"><div class="section-kicker">${esc(t.accessEye)}</div><h2>${esc(t.accessTitle)}</h2><p>${esc(t.accessText)}</p><form id="license-form"><label>${esc(t.license)}<input id="license-key" autocomplete="off" placeholder="${esc(t.licensePlaceholder)}"></label><label class="check"><input id="remember-key" type="checkbox"> <span>${esc(t.remember)}</span></label><button class="button gold" type="submit">${esc(t.unlock)} <span>→</span></button><p id="license-status" class="feedback"></p></form>${cfg.salesEnabled&&cfg.payhipUrl?`<p class="fine"><a href="${esc(cfg.payhipUrl)}">${esc(t.needKey)}</a> · ${esc(t.keyHelp)}</p>`:`<p class="fine">${esc(t.accessUnavailable)}</p>`}</section>`}
  function home(){shell(`<section class="hero"><div class="section-kicker">${esc(t.eyebrow)}</div><h1>${esc(t.heroA)}<br><em>${esc(t.heroB)}</em></h1><p>${esc(t.heroText)}</p><div class="hero-actions"><a class="button gold" href="#calculator">${esc(t.tryDemo)} <span>→</span></a><a class="button ghost" href="${path('learn.html')}">${esc(t.openCourse)}</a></div><div class="strip">${t.strip.map(x=>`<span>${esc(x)}</span>`).join('')}</div></section>${calculator()}${trailer()}${practice()}${offer()}<section class="book panel"><div><div class="section-kicker">${esc(t.bookEye)}</div><h2>${esc(t.bookTitle)}</h2><p>${esc(t.bookText)}</p></div><a class="button ghost" href="${esc(cfg.bookUrl)}" target="_blank" rel="noopener">${esc(t.bookButton)} <span>↗</span></a></section>${access()}<section class="origin"><p>${esc(t.origin)}</p></section>`); bindHome();}
  function bindHome(){
    const form=document.getElementById('calc-form'); form.addEventListener('submit',e=>{e.preventDefault();const d=+document.getElementById('calc-day').value,m=+document.getElementById('calc-month').value,y=+document.getElementById('calc-year').value,out=document.getElementById('calc-result');if(!M.valid(y,m,d)){out.innerHTML=`<span class="error">${esc(t.invalidDate)}</span>`;return}const w=M.weekday(y,m,d);out.innerHTML=`<strong>${esc(dateLabel(y,m,d))}</strong><span>${esc(weekdayName(w))}</span><small>${esc(t.us)}: ${String(m).padStart(2,'0')}/${String(d).padStart(2,'0')}/${y}</small>`}); form.dispatchEvent(new Event('submit'));
    const update=()=>{const y=+document.getElementById('trailer-year').value||2026; if(y<1||y>9999)return;[['pair-day',4,4],['reverse-day',9,5],['july-day',11,7],['pi-day',14,3]].forEach(([id,d,m])=>document.getElementById(id).textContent=weekdayName(M.weekday(y,m,d)));}; document.getElementById('trailer-year').addEventListener('input',update);update();
    document.querySelectorAll('#demo-choices button').forEach(b=>b.addEventListener('click',()=>{const ok=+b.dataset.answer===M.weekday(2026,6,6),f=document.getElementById('demo-feedback');f.textContent=ok?t.demoCorrect:t.demoWrong;f.className='feedback '+(ok?'good':'bad')}));
    let mode=0,q=null,score=0,streak=0; const qbox=document.getElementById('practice-question'); const newQ=()=>{if(mode===0){const y=Math.floor(Math.random()*400)+1800;q={y,ans:M.centuryAnchor(y),text:fmt(t.centuryQuestion,{year:y})}}else if(mode===1){const y=Math.floor(Math.random()*400)+1800;q={y,ans:M.details(y,3,14).z,text:fmt(t.yearQuestion,{year:y})}}else{const d=M.randomDate();q={...d,ans:M.weekday(d.year,d.month,d.day),text:`${dateLabel(d.year,d.month,d.day)} — ${t.dateQuestion}`}} qbox.innerHTML=`<h3>${esc(q.text)}</h3>`;document.getElementById('practice-feedback').textContent='';}; document.querySelectorAll('.practice-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.practice-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=+b.dataset.mode;newQ()}));document.getElementById('practice-check').addEventListener('click',()=>{const v=+document.getElementById('practice-answer').value,f=document.getElementById('practice-feedback');if(v===q.ans){score++;streak++;f.textContent=t.solved;f.className='feedback good'}else{streak=0;f.textContent=t.practiceWrong;f.className='feedback bad'}document.getElementById('practice-score').textContent=score;document.getElementById('practice-streak').textContent=streak});document.getElementById('practice-new').addEventListener('click',newQ);newQ();
    const lf=document.getElementById('license-form');lf.addEventListener('submit',async e=>{e.preventDefault();const s=document.getElementById('license-status'),key=document.getElementById('license-key').value.trim();if(!key){s.textContent=t.missingKey;s.className='feedback bad';return} if(!cfg.salesEnabled||!cfg.apiBase){s.textContent=t.accessUnavailable;s.className='feedback';return} s.textContent=t.checking;s.className='feedback';try{const r=await fetch(cfg.apiBase.replace(/\/$/,'')+'/v1/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.code||'invalid');if(document.getElementById('remember-key').checked)localStorage.setItem('bday-license',key);sessionStorage.setItem('bday-token',j.token);location.href=path('learn.html')}catch(err){s.textContent=err.message==='invalid'?t.licenseInvalid:t.networkError;s.className='feedback bad'}});
  }
  async function learn(){shell(`<section class="hero compact"><div class="section-kicker">${esc(t.courseEye)}</div><h1>${esc(t.courseTitle)}</h1><p>${esc(t.courseIntro)}</p></section><section id="learn-app" class="learn-app panel"><p>${esc(t.checking)}</p></section>`);const app=document.getElementById('learn-app');if(!cfg.salesEnabled||!cfg.apiBase){app.innerHTML=`<div class="locked"><h2>${esc(t.accessTitle)}</h2><p>${esc(t.accessUnavailable)}</p><a class="button gold" href="${path('index.html')}#access">${esc(t.needKey)}</a></div>`;return}let token=sessionStorage.getItem('bday-token');const key=localStorage.getItem('bday-license');if(!token&&key){try{const r=await fetch(cfg.apiBase.replace(/\/$/,'')+'/v1/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key})});const j=await r.json();if(r.ok&&j.ok){token=j.token;sessionStorage.setItem('bday-token',token)}}catch(_){}}if(!token){app.innerHTML=`<div class="locked"><h2>${esc(t.accessTitle)}</h2><p>${esc(t.keyHelp)}</p><a class="button gold" href="${path('index.html')}#access">${esc(t.unlock)}</a></div>`;return}try{const r=await fetch(cfg.apiBase.replace(/\/$/,'')+'/v1/course?lang='+encodeURIComponent(lang),{headers:{authorization:'Bearer '+token}});if(!r.ok)throw new Error();const data=await r.json();renderCourse(app,data,token)}catch(_){app.innerHTML=`<div class="locked"><p>${esc(t.providerUnavailable)}</p><a class="button ghost" href="${path('index.html')}#access">${esc(t.back)}</a></div>`}}
  function renderCourse(app,data,token){const lessons=data.lessons||[],key='bday-progress-'+lang;let done=JSON.parse(localStorage.getItem(key)||'[]');const draw=()=>{app.innerHTML=`<div class="course-toolbar"><div><span class="section-kicker">${esc(t.progress)}</span><strong>${fmt(t.lessonCount,{n:done.length})}</strong></div><button class="button ghost small" id="logout">${esc(t.logout)}</button></div><div class="lesson-grid">${lessons.map((l,i)=>`<button class="lesson-card ${done.includes(i)?'done':''}" data-lesson="${i}"><span>${String(i+1).padStart(2,'0')}</span><div><b>${esc(l.title||t.lessonTitles[i])}</b><small>${done.includes(i)?esc(t.completed):esc(t.lesson)}</small></div><i>${done.includes(i)?'✓':'→'}</i></button>`).join('')}</div><div id="lesson-view" class="lesson-view"></div>`;document.querySelectorAll('.lesson-card').forEach(b=>b.addEventListener('click',()=>open(+b.dataset.lesson)));document.getElementById('logout').addEventListener('click',()=>{sessionStorage.removeItem('bday-token');location.href=path('index.html')});};const open=i=>{const l=lessons[i],view=document.getElementById('lesson-view'),qs=l.questions||[],q=qs[0]||{};view.innerHTML=`<div class="lesson-content"><span class="section-kicker">${esc(t.lesson)} ${i+1}</span><h2>${esc(l.title||t.lessonTitles[i])}</h2>${(l.paragraphs||[]).map(p=>`<p>${esc(p)}</p>`).join('')}${l.example?`<div class="worked"><b>${esc(t.worked)}</b><p>${esc(l.example)}</p></div>`:''}<div class="checkpoint"><b>${esc(t.checkpoint)}</b><p>${esc(q.prompt||'')}</p><div class="choices">${(q.options||[]).map((o,j)=>`<button data-i="${j}">${esc(o)}</button>`).join('')}</div><p class="feedback" id="lesson-feedback"></p></div><button class="button gold" id="complete-lesson">${esc(done.includes(i)?t.nextLesson:t.check)}</button></div>`;view.querySelectorAll('.choices button').forEach(b=>b.addEventListener('click',()=>{view.querySelectorAll('.choices button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));document.getElementById('complete-lesson').addEventListener('click',()=>{const selected=view.querySelector('.choices button.selected');if(!selected)return;const ok=+selected.dataset.i===q.answer;const f=document.getElementById('lesson-feedback');f.textContent=ok?t.lessonPassed:t.notYet;f.className='feedback '+(ok?'good':'bad');if(ok&&!done.includes(i)){done.push(i);done.sort();localStorage.setItem(key,JSON.stringify(done));setTimeout(draw,550)}})};draw();if(lessons.length)open(done.length<lessons.length?Math.max(0,done.length):lessons.length-1)}
  function simplePage(kind){const legal=kind==='legal';shell(`<section class="page-copy"><div class="section-kicker">${esc(legal?t.legal:t.privacy)}</div><h1>${esc(legal?t.legalTitle:t.privacyTitle)}</h1><div class="copy-grid">${legal?`<h2>${esc(t.editor)}</h2><p>${esc(cfg.owner)} · ${esc(cfg.businessForm)}<br>${esc(cfg.address)}<br><a href="mailto:${esc(cfg.email)}">${esc(cfg.email)}</a> · ${esc(cfg.phone)}</p><h2>${esc(t.hosting)}</h2><p>${esc(cfg.hostingName)} · ${esc(cfg.hostingAddress)}<br><a href="${esc(cfg.hostingUrl)}">${esc(cfg.hostingUrl)}</a></p><h2>${esc(t.rightsTitle)}</h2><p>${esc(t.rightsText)}</p><h2>${esc(t.legal)}</h2><p>${esc(t.licenseTerms)}</p><p>${esc(t.methodNote)}</p>`:`<p>${esc(t.privacyIntro)}</p><h2>${esc(t.privacyStorage)}</h2><p>${esc(t.privacyLicense)}</p><h2>${esc(t.privacyProviders)}</h2><p>${esc(t.privacyContact)}</p><button class="button ghost" id="clear-data">${esc(t.clearData)}</button>`}</div></section>`);if(!legal)document.getElementById('clear-data').addEventListener('click',()=>{if(confirm(t.clearConfirm)){localStorage.clear();sessionStorage.clear();alert(t.cleared);location.reload()}})}
  if(page==='home')home(); else if(page==='learn')learn(); else if(page==='legal')simplePage('legal'); else if(page==='privacy')simplePage('privacy'); else shell(`<section class="page-copy"><h1>${esc(t.notFound)}</h1><a class="button gold" href="${path('index.html')}">${esc(t.goHome)}</a></section>`);
})();
